runtime: php81
env: flex

runtime_config:
  document_root: public

skip_files:
  - .env

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1

resources:
  cpu: 2
  memory_gb: 2
  disk_size_gb: 25

env_variables:
  APP_DEBUG: true
  APP_ENV: production
  APP_KEY: base64:B/TCTTH2wEy4Ama6I+jBIuZI9bFujpHIxCjcETfHbOI=
  APP_NAME: "Example App - GAE"

  LOG_LEVEL: debug
